default: &defaults
  ignore_user_agent_locale: false
  display_user_avatars: false
  default_user_avatar: 'identicon'
  user_avatar_api_url: ''
  gpg_mail_private_key_passphrase: '' 
  gpg_mail_encryption_required: false
  gpg_mail_verification_required: false
  gpg_key_server: "https://pgp.mit.edu/"
  gpg_mail_always_sign_outgoing_mail: false 
  gpg_mail_always_encrypt_outgoing_mail: false 
  gpg_mail_ignore_bad_signature: false 

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
